$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: taxi-fare-online
model: azureml:taxi-model@latest
code_configuration:
  code: .
  scoring_script: score.py
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
  conda_file: online-conda.yml
environment_variables:
  MONITORING_STORAGE_ACCOUNT: "REPLACE_AT_DEPLOY_TIME"
instance_type: Standard_DS3_v2
instance_count: 1
egress_public_network_access: enabled
